<?php
return [
        'name' => 'Kawi Studio',
        'menu_setting' => 'administrator',
        'developer_setting' => 'developer',
        'logo' => 'kawi_logo.png',
        'project' => 'core',
        'favicon' => 'NewCore_favicon.ico',
        'error' => 'error.png',
        'backend' => 'default',
        'frontend' => 'divisima',
        'email' => 'itok.toni@gmail.com',
        'seo' => 'seo',
        'description' => '<p>Donec vitae purus nunc. Morbi faucibus erat sit amet congue mattis. Nullam frin-gilla faucibus urna, id dapibus erat iaculis ut. Integer ac sem.</p><p>Donec vitae purus nunc. Morbi faucibus erat sit amet congue mattis. Nullam frin-gilla faucibus urna, id dapibus erat iaculis ut. Integer ac sem.</p>',
        'owner' => 'Alexandro',
        'service' => null,
        'address' => '<p>Jl. Tanah Koja RT. 001/02 No. 65 </p><p>Kel. Duri Kosambi, Kec. Cengkareng, Jakarta Barat</p>',
        'header' => '&lt;p&gt;&lt;br&gt;&lt;/p&gt;',
        'color' => 'F51167',
        'footer' => 'Copyright ©2019 All rights reserved | This template is made with by Colorlib',
        'phone' => '(+62 21) 345321',
        'install' => '0',
        'province' => '6',
        'city' => '151',
        'pjax' => false,
        'loading' => false,
        'public' => 'public',
        'secure' => true,
        'live' => '1',
        'contact' => '',
        'about' => "&lt;h2 class=&quot;p-title&quot; style=&quot;margin: 0px 0px 18px; font-family: &quot;Josefin Sans&quot;, sans-serif; font-weight: 700; line-height: 1.2; color: rgb(65, 65, 65); font-size: 18px; text-transform: uppercase; letter-spacing: normal;&quot;&gt;WHITE PEPLUM TOP&lt;/h2&gt;&lt;div class=&quot;panel&quot; style=&quot;color: rgb(33, 37, 41); font-family: &quot;Josefin Sans&quot;, sans-serif; font-size: 16px; background-color: rgb(255, 255, 255);&quot;&gt;&lt;div class=&quot;panel-header&quot; id=&quot;headingOne&quot;&gt;&lt;/div&gt;&lt;div aria-labelledby=&quot;headingOne&quot; data-parent=&quot;#accordion&quot;&gt;&lt;div class=&quot;panel-body&quot;&gt;&lt;p style=&quot;margin-bottom: 1rem; font-size: 14px; color: rgb(88, 88, 88); line-height: 1.6;&quot;&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra tempor so dales. Phasellus sagittis auctor gravida. Integer bibendum sodales arcu id te mpus. Ut consectetur lacus leo, non scelerisque nulla euismod nec.&lt;/p&gt;&lt;p style=&quot;margin-bottom: 1rem; font-size: 14px; color: rgb(88, 88, 88); line-height: 1.6;&quot;&gt;Approx length 66cm/26&quot; (Based on a UK size 8 sample)&lt;/p&gt;&lt;p style=&quot;margin-bottom: 1rem; font-size: 14px; color: rgb(88, 88, 88); line-height: 1.6;&quot;&gt;Mixed fibres&lt;/p&gt;&lt;p style=&quot;margin-bottom: 1rem; font-size: 14px; color: rgb(88, 88, 88); line-height: 1.6;&quot;&gt;The Model wears a UK size 8/ EU size 36/ US size 4 and her height is 5'8&quot;&lt;/p&gt;&lt;p style=&quot;margin-bottom: 1rem; font-size: 14px; color: rgb(88, 88, 88); line-height: 1.6;&quot;&gt;Lorem, ipsum dolor sit amet consectetur adipisicing elit. Commodi quae possimus vero, facilis eius dolore asperiores libero at debitis quisquam quis sed, nulla maiores quas eum. Quod qui voluptatem consectetur.&lt;/p&gt;&lt;p style=&quot;margin-bottom: 1rem; font-size: 14px; color: rgb(88, 88, 88); line-height: 1.6;&quot;&gt;Lorem ipsum dolor, sit amet consectetur adipisicing elit. Architecto rem sit incidunt voluptatem adipisci saepe perspiciatis sunt ut doloribus eum autem necessitatibus accusantium, quasi ex repellat tempore mollitia quibusdam ullam. Libero necessitatibus doloremque, ipsam provident aut quia iure? Inventore, eveniet culpa illo asperiores recusandae commodi assumenda. Et quasi aut tenetur, dicta, dolores vel aliquam similique laudantium repellat quod deleniti natus! Maxime ducimus quam ab nesciunt animi repellat, quod facere quas. Necessitatibus, soluta cumque id quae dolor fuga officia harum. Aliquid a suscipit reiciendis, pariatur delectus quisquam id fugiat consequuntur eos?&lt;/p&gt;&lt;p style=&quot;margin-bottom: 1rem; font-size: 14px; color: rgb(88, 88, 88); line-height: 1.6;&quot;&gt;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam nostrum numquam omnis laborum ut voluptas eveniet cum, magni, tempore commodi odio saepe delectus porro exercitationem rerum! Enim, nemo eaque. Nesciunt!&lt;/p&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;",
        'autonumber' => 12,
        'pagination' => 10,
        'button' => 50,
        'cache' => '1000', //16jam
        'session' => '',
        'env' => 'local',
        'debug' => '1',
        'editor' => false,
        'latitude' => '-7.791972',
        'langitude' => '110.467309',
        'asset' => false,
];
